import { Request } from 'puppeteer';
import { ILogger } from './common/Logger';
import { IRequestBlocker } from './interface/IRequestBlocker';
import { IRequestModifier } from './interface/IRequestModifier';
import { IRequestSpy } from './interface/IRequestSpy';
import { IResponseFaker } from './interface/IResponseFaker';
import { RequestMatcher } from './types/RequestMatcher';
export declare class RequestInterceptor {
    private requestSpies;
    private responseFakers;
    private requestModifiers;
    private matcher;
    private logger;
    private requestBlocker;
    constructor(matcher: RequestMatcher, logger?: ILogger);
    intercept(interceptedRequest: Request): Promise<void>;
    addSpy(requestSpy: IRequestSpy): void;
    addFaker(responseFaker: IResponseFaker): void;
    addRequestModifier(requestModifier: IRequestModifier): void;
    block(urlsToBlock: Array<string> | string): void;
    clearSpies(): void;
    clearFakers(): void;
    clearRequestModifiers(): void;
    clearUrlsToBlock(): void;
    setUrlsToBlock(urlsToBlock: Array<string>): void;
    setRequestBlocker(requestBlocker: IRequestBlocker): void;
    private getMatchingFaker;
    private matchSpies;
    private getMatchingOverride;
    private blockUrl;
    private acceptUrl;
}
